# Generated by Django 3.2.8 on 2022-12-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='apellidos',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='nombre',
            new_name='name',
        ),
        migrations.AddField(
            model_name='paciente',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='diagnosis',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sex',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sicks',
            field=models.CharField(default='', max_length=500),
        ),
    ]
