# Generated by Django 3.2.8 on 2022-12-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221228_1619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paciente',
            new_name='Pacient',
        ),
    ]
