# Generated by Django 3.2.8 on 2022-12-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrequest',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
